name: Windows2022

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-2022

    timeout-minutes: 9999

    steps:

    - name: Downloading Ngrok.

      run: |

        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

        Invoke-WebRequest https://raw.githubusercontent.com/r00tsamsepi0l00/VPS-2022/main/start.bat -OutFile start.bat

        Invoke-WebRequest https://raw.githubusercontent.com/r00tsamsepi0l00/VPS-2022/main/wallpaper.png -OutFile wallpaper.bmp

        Invoke-WebRequest https://raw.githubusercontent.com/r00tsamsepi0l00/VPS-2022/main/wallpaper.bat -OutFile wallpaper.bat

        Invoke-WebRequest https://raw.githubusercontent.com/r00tsamsepi0l00/VPS-2022/main/loop.ps1 -OutFile loop.ps1

    - name: Downloading Launcher.

      run: |

        Invoke-WebRequest https://raw.githubusercontent.com/r00tsamsepi0l00/VPS-2022/main/launcher/Node.js.lnk -OutFile Node.js.lnk

    - name: Mengextract Ngrok File.

      run: Expand-Archive ngrok.zip

    - name: Connect Ke Akun Ngrok.

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: RDP Access.

      run: | 

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

        copy wallpaper.bmp D:\a\wallpaper.bmp

        copy wallpaper.bat D:\a\wallpaper.bat

        copy Node.js.lnk C:\Users\Public\Desktop\Node.js.lnk

    - name: Creating Tunnel.

      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region in 3389"'

    - name: Connect Ke RDP Kamu CPU 2 Core - 7GB Ram - 255 SSD.

      run: cmd /c start.bat

    - name: Looping

      run: | 

        Invoke-WebRequest https://raw.githubusercontent.com/r00tsamsepi0l00/VPS-2022/main/loop.ps1 -OutFile loop.ps1

        ./loop.ps1
